### ISSUE TITLE
trocar Either por um tipo com construtores explicitos

### ISSUE THREAD

**Issue by petrolifero** [mpjmuniz/pilib-hs-c20182#1]
Semanticamente, Either a b representa uma computação que pode dar certo, retornando tipo b, ou um erro, retornando tipo a.

Podemos entende-lo como uma evolução do Maybe. Com Maybe podemos saber se a computação falhou. Com Either, podemos saber o porquê.

Esse tipo ocorre no Parser.hs, na linha 125, na definição do tipo Storable. Sugiro, por uma questão de semantica, mudar para data `Storable = B Bool | I Int` ou algo assim.

Não estou adicionando construtores, apenas mudando seus nomes para ficar mais parecido com o padrão do haskell. Vai facilitar outros programadores que, ao verem seu codigo, vão poder inspecionar menos pois supõem que vocês seguiram o padrão. 

Boa sorte com o projeto, estão indo bem

**Comment by mpjmuniz** [comment]
Fala João, obrigado pela sugestão. 

olhando pro construtor a mudança é clara. No entanto, o tipo Storable usa duas funções de mapeamento para Value, evalStorable e storeValue. Você pode me ajudar com um jeito elegante que use esta nova construção proposta, sem precisar destas 2 funções?

**Comment by petrolifero** [comment]
Eu pesquisei e aparentemente não. A tipagem do Haskell exige algo nessa linha.

Desculpe

**Comment by mpjmuniz** [comment]
Entendi. Neste caso vou só trocar a implementação destas funções e seguir sua sugestão. Obrigado.
